### ISSUE TITLE
Key error 

### ISSUE THREAD

**Issue by Exzellenz** [foxypool/foxy-gh-farmer#1]
Hi there seems to be a problem with the key  connect_to_unknown_peers in foxy_chia_config_manager.py
in all of my machines Ubuntu and Windows  at least that key was not defined in the chia config which led to key  error on launching the farmer:
`Traceback (most recent call last):
  File "foxy_gh_farmer\foxy_gh_farmer_main.py", line 162, in <module>
  File "foxy_gh_farmer\foxy_gh_farmer_main.py", line 158, in main
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1635, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "foxy_gh_farmer\foxy_gh_farmer_main.py", line 141, in cli
  File "click\core.py", line 781, in forward
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "foxy_gh_farmer\foxy_gh_farmer_main.py", line 147, in run_cmd
  File "chia\server\start_service.py", line 317, in async_run
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "foxy_gh_farmer\foxy_gh_farmer_main.py", line 120, in run_foxy_gh_farmer
  File "foxy_gh_farmer\foxy_gh_farmer_main.py", line 48, in start
  File "foxy_gh_farmer\foxy_chia_config_manager.py", line 66, in ensure_foxy_config
  File "foxy_gh_farmer\foxy_chia_config_manager.py", line 125, in update_foxy_chia_config_from_foxy_config
KeyError: 'connect_to_unknown_peers'
[12060] Failed to execute script 'foxy_gh_farmer_main' due to unhandled exception!
`

**Comment by felixbrucker** [comment]
Thanks for reporting 👍

**Comment by felixbrucker** [comment]
Looks like the key is missing in configs generated before chia 1.3.0, will be fixed in 1.0.1
