### ISSUE TITLE
SSL Issue with foxy-gh-farmer ??

### ISSUE THREAD

**Issue by whattheflux** [foxypool/foxy-gh-farmer#2]
Hi,
I've copied my mainnet folder from chia (I was using machinaris) to /root/.foxy-gh-farmer) and created the config.yaml but when I run ./foxy-gh-farmer I get the following error. Can anybody help?

Downloading Gigahorse 1.8.2.giga14 ..
Traceback (most recent call last):
  File "aiohttp/connector.py", line 980, in _wrap_create_connection
  File "asyncio/base_events.py", line 1112, in create_connection
  File "asyncio/base_events.py", line 1145, in _create_connection_transport
  File "asyncio/sslproto.py", line 575, in _on_handshake_complete
  File "asyncio/sslproto.py", line 557, in _do_handshake
  File "ssl.py", line 979, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "foxy_gh_farmer/foxy_gh_farmer_main.py", line 162, in <module>
  File "foxy_gh_farmer/foxy_gh_farmer_main.py", line 158, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1635, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "foxy_gh_farmer/foxy_gh_farmer_main.py", line 141, in cli
  File "click/core.py", line 781, in forward
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "foxy_gh_farmer/foxy_gh_farmer_main.py", line 147, in run_cmd
  File "chia/server/start_service.py", line 317, in async_run
  File "asyncio/runners.py", line 190, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 653, in run_until_complete
  File "foxy_gh_farmer/foxy_gh_farmer_main.py", line 120, in run_foxy_gh_farmer
  File "foxy_gh_farmer/foxy_gh_farmer_main.py", line 63, in start
  File "foxy_gh_farmer/gigahorse_launcher.py", line 74, in create_start_daemon_connection
  File "foxy_gh_farmer/gigahorse_launcher.py", line 51, in launch_start_daemon
  File "foxy_gh_farmer/gigahorse_binary_manager.py", line 35, in get_binary_directory_path
  File "foxy_gh_farmer/gigahorse_binary_manager.py", line 58, in _download_release
  File "aiohttp/client.py", line 1141, in __aenter__
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 901, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1175, in _create_direct_connection
  File "aiohttp/connector.py", line 982, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
[14415] Failed to execute script 'foxy_gh_farmer_main' due to unhandled exception!

**Comment by felixbrucker** [comment]
Which OS are you using, and which version of python?
Or is this happening in the docker image?

**Comment by whattheflux** [comment]
Unraid 6.11.5
Python 2.7.18
Python3 3.9.6

Just running it in the console on unraid. No docker.

**Comment by felixbrucker** [comment]
I have pushed a potential fix to main, can you verify the issue does not happen anymore when running from main?

**Comment by whattheflux** [comment]
ahh thankyou but I'm using the binary. Unraid errors out when trying to use from source :(

**Comment by felixbrucker** [comment]
Ah i see, you can use the ubuntu artifact at the bottom of this page for testing: https://github.com/foxypool/foxy-gh-farmer/actions/runs/6485053813

**Comment by whattheflux** [comment]
Working I think. No further errors. I'm still using flexpool at the moment and throwing some difficulty errors, but will let it run and see what happens.
Thankyou for your rapid replies/fix!

**Comment by felixbrucker** [comment]
Great thanks for confirming 👍

**Comment by felixbrucker** [comment]
Fixed with https://github.com/foxypool/foxy-gh-farmer/commit/18c58b137cecfc16b7ee4a68556c0bae35cdc6a4
