### ISSUE TITLE
foxy-gh-farmer join-pool   failed?

### ISSUE THREAD

**Issue by liliput629** [foxypool/foxy-gh-farmer#3]
Hi I couldn't join-pool , i can launch foxy-gh-farmer but not comunicate to foxy-pool correctly, 

Debian 11.6
I ve compiled foxy-gh-farmer 1.1

root@rock-4c-plus:/chia/foxy-gh-farmer# sudo foxy-gh-farmer join-pool
Daemon not started yet
Starting daemon
chia_wallet: started
Connection error. Check if wallet rpc is running at 29256
This is normal if wallet is still starting up
Exception from 'wallet' :
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/chia/cmds/cmds_util.py", line 106, in get_any_service_client
    yield None, config
  File "/usr/local/lib/python3.9/dist-packages/foxy_gh_farmer/cmds/join_pool.py", line 53, in join_pool
    assert wallet_client is not None
AssertionError

Daemon stopped

File "/usr/local/lib/python3.9/dist-packages/chia/cmds/cmds_util.py", line 106, in get_any_service_client
    yield None, config

**Comment by felixbrucker** [comment]
Did you run `foxy-gh-farmer` 1.1 before running the `join-pool` command? it needs to initialize the chia install before being able to join the pool

**Comment by liliput629** [comment]
i have try again, and i see the same log,

when i use 'sudo' , the same log.

In this computer i have used previously flexfarmer, runing , i don't have installed Chia’s Application

when i start foxy-gh-farmer   the logfile, same correcte, but foxy-pool farmer web page don't see the worker.


thanks

**Comment by felixbrucker** [comment]
i see, did you add your keys yet?

See step 3 for Foxy-GH-Farmer: https://docs.foxypool.io/proof-of-spacetime/guides/switching-from-flex-farmer-to-foxy/

**Comment by liliput629** [comment]
if I did point 3 and the keys were generated correctly,
I have 3 machines in windows that the foxy-gh-farmer works correctly, migrated from flexpool

the one from debian seems to work but it doesn't connect properly to the pool, 


this is the log, which seems to work:

radxa@rock-4c-plus:/chia/foxy-gh-farmer$ foxy-gh-farmer  -c foxy-gh-farmer.yaml
2023-10-18T20:38:24.028 foxy_gh_farmer main               : INFO     Foxy-GH-Farmer 1.1.0 using config in /chia/foxy-gh-farmer/foxy-gh-farmer.yaml
chia_farmer: started
chia_harvester: started
2023-10-18T20:38:28.423 foxy_gh_farmer farmer             : INFO     chia-blockchain version: 1.8.2
2023-10-18T20:38:28.426 foxy_gh_farmer farmer             : INFO     Service capabilities: [(1, '1'), (2, '1'), (3, '1')]
2023-10-18T20:38:28.741 foxy_gh_farmer harvester          : INFO     Starting service harvester ...
2023-10-18T20:38:28.744 foxy_gh_farmer harvester          : INFO     chia-blockchain version: 1.8.2
2023-10-18T20:38:28.747 foxy_gh_farmer harvester          : INFO     Service capabilities: [(1, '1'), (2, '1'), (3, '1')]
2023-10-18T20:38:28.760 foxy_gh_farmer harvester          : INFO     Started harvester service on network_id: mainnet at port 28448
2023-10-18T20:38:28.779 foxy_gh_farmer harvester          : INFO     Add resolved PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=28447)
2023-10-18T20:38:28.787 foxy_gh_farmer harvester          : INFO     Cannot connect to host 127.0.0.1:28447 ssl:<ssl.SSLContext object at 0xffff9e77cb40> [Connect call failed ('127.0.0.1', 28447)]
2023-10-18T20:38:28.790 foxy_gh_farmer harvester          : INFO     Failed to connect to PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=28447)
2023-10-18T20:38:28.820 foxy_gh_farmer daemon             : INFO     registered for service chia_harvester
2023-10-18T20:38:28.823 foxy_gh_farmer daemon             : INFO     {'success': True}
2023-10-18T20:38:28.924 foxy_gh_farmer farmer             : INFO     Started listening on port: 28447
2023-10-18T20:38:28.926 foxy_gh_farmer farmer             : INFO     Started farmer service on network_id: mainnet at port 28447
2023-10-18T20:38:28.956 foxy_gh_farmer farmer             : INFO     Add resolved PeerInfo(_ip=IPv4Address('185.205.246.74'), _port=18445)
2023-10-18T20:38:29.170 foxy_gh_farmer farmer             : INFO     Connected with full_node PeerInfo(_ip=IPv4Address('185.205.246.74'), _port=18445)
2023-10-18T20:38:29.317 foxy_gh_farmer daemon             : INFO     Register service {'service': 'chia_farmer'}
2023-10-18T20:38:29.320 foxy_gh_farmer daemon             : INFO     registered for service chia_farmer
2023-10-18T20:38:29.322 foxy_gh_farmer daemon             : INFO     {'success': True}
2023-10-18T20:38:31.890 foxy_gh_farmer harvester          : INFO     Connected with farmer PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=28447)
2023-10-18T20:38:36.043 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/750GB-WD-02/chia_nft does not exist.
2023-10-18T20:38:36.051 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/1TB-TO-01/chia_nft does not exist.
2023-10-18T20:38:36.058 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/1TB-TO-02/chia_nft does not exist.
2023-10-18T20:38:36.065 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/1TB-TO-03/chia_nft does not exist.
2023-10-18T20:38:36.074 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/1TB-TO-04/chia_nft does not exist.
2023-10-18T20:38:36.081 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/1TB-TO-05/chia_nft does not exist.
2023-10-18T20:38:38.962 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/1TB-WD-01/chia_nft does not exist.
2023-10-18T20:38:38.969 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/1TB-WD-02/chia_nft does not exist.
2023-10-18T20:38:38.977 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/1TB-ST-01/chia_nft does not exist.
2023-10-18T20:38:38.984 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/1TB-KIN-01/chia_nft does not exist.
2023-10-18T20:38:39.504 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 7b6dc93f99... Found 0 proofs. Time: 0.00094 s. Total 0 plots
2023-10-18T20:38:43.339 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/WD-12/chia_nft does not exist.
2023-10-18T20:38:44.054 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/TO-20/chia_nft does not exist.
2023-10-18T20:38:44.069 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/TO-22/chia_nft does not exist.
2023-10-18T20:38:44.077 foxy_gh_farmer harvester          : WARNING  Directory: /media/chia/TO-23/chia_nft does not exist.
2023-10-18T20:38:44.085 foxy_gh_farmer harvester          : INFO     _plot_refresh_callback: event started, loaded 0, removed 0, processed 0, remaining 99, duration: 0.00 seconds, total plots: 0
2023-10-18T20:38:44.127 foxy_gh_farmer farmer             : INFO     reset: node_id cae5dd985ef4427960f5a8b7b501f6054177f81a549a8dad83fd02fbc9a00847, current_sync: [state 0, sync_id 0, next_message_id 0, plots_processed 0, plots_total 0, delta [valid +0/-0, invalid +0/-0, keys missing: +0/-0, duplicates: +0/-0], time_done None]
2023-10-18T20:38:47.403 foxy_gh_farmer harvester          : INFO     _plot_refresh_callback: event done, loaded 99, removed 0, processed 99, remaining 0, duration: 3.31 seconds, total plots: 99
2023-10-18T20:38:47.465 foxy_gh_farmer harvester          : INFO     Saved 100877 bytes of cached data
2023-10-18T20:38:48.206 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 7b6dc93f99... Found 0 proofs. Time: 0.02863 s. Total 99 plots
2023-10-18T20:38:57.060 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 7b6dc93f99... Found 0 proofs. Time: 0.05174 s. Total 99 plots
2023-10-18T20:39:05.941 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 7b6dc93f99... Found 0 proofs. Time: 0.08836 s. Total 99 plots
2023-10-18T20:39:17.092 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 7b6dc93f99... Found 0 proofs. Time: 0.07826 s. Total 99 plots
2023-10-18T20:39:26.952 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.06433 s. Total 99 plots
2023-10-18T20:39:36.502 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.04998 s. Total 99 plots
2023-10-18T20:39:46.257 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.07230 s. Total 99 plots
2023-10-18T20:39:57.948 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.08199 s. Total 99 plots
2023-10-18T20:40:06.695 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.08238 s. Total 99 plots
2023-10-18T20:40:15.602 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.05930 s. Total 99 plots
2023-10-18T20:40:25.708 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.07609 s. Total 99 plots
2023-10-18T20:40:35.265 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.02833 s. Total 99 plots
2023-10-18T20:40:45.489 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.08533 s. Total 99 plots
2023-10-18T20:40:57.082 foxy_gh_farmer harvester          : INFO     1 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 1.38631 s. Total 99 plots
2023-10-18T20:41:05.541 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.05088 s. Total 99 plots
2023-10-18T20:41:14.534 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.05365 s. Total 99 plots
2023-10-18T20:41:23.419 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.08232 s. Total 99 plots
2023-10-18T20:41:33.892 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.08379 s. Total 99 plots
2023-10-18T20:41:41.942 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.08168 s. Total 99 plots
2023-10-18T20:41:51.024 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.04930 s. Total 99 plots
2023-10-18T20:42:00.558 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.05961 s. Total 99 plots
2023-10-18T20:42:09.636 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.08538 s. Total 99 plots
2023-10-18T20:42:20.969 foxy_gh_farmer harvester          : INFO     1 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 2.35351 s. Total 99 plots
2023-10-18T20:42:28.609 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.10153 s. Total 99 plots
2023-10-18T20:42:28.626 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.06159 s. Total 99 plots
2023-10-18T20:42:37.308 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.02846 s. Total 99 plots
2023-10-18T20:42:46.713 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.07936 s. Total 99 plots
2023-10-18T20:42:55.900 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.07845 s. Total 99 plots
2023-10-18T20:43:04.906 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.08681 s. Total 99 plots
2023-10-18T20:43:13.820 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.08335 s. Total 99 plots
2023-10-18T20:43:22.605 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming 98eb627ea8... Found 0 proofs. Time: 0.05563 s. Total 99 plots
2023-10-18T20:43:32.726 foxy_gh


thanks

**Comment by felixbrucker** [comment]
Ah yes, the plotnfts are missing in the config.yaml (`pool_list`), doing a `foxy-gh-farmer join-pool` on that machine should solve the issue. Alternatively you can copy the `pool_list` from a working farmer as well

**Comment by liliput629** [comment]
Hello,
I copied the contents of "pool_list" into config.yml

and it works properly

but using "foxy-gh-farmer join-pool" hangs,


thanks

**Comment by felixbrucker** [comment]
Startup can take a bit, like up to 5-10 sec

Can you check the `debug.log` in `~/.foxy-gh-farmer/mainnet/log/` for additional info on this?

**Comment by liliput629** [comment]
I don't find any old log , when launch foxy-gh-farmer join-pool

when i ve launched again with config.yml modified, the first time has failed, without debug.log info,

radxa@rock-4c-plus:/chia/foxy-gh-farmer$ sudo foxy-gh-farmer join-pool
[sudo] password for radxa:
Daemon not started yet
Starting daemon
chia_wallet: started
Connection error. Check if wallet rpc is running at 29256
This is normal if wallet is still starting up
Exception from 'wallet' :
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/chia/cmds/cmds_util.py", line 106, in get_any_service_client
    yield None, config
  File "/usr/local/lib/python3.9/dist-packages/foxy_gh_farmer/cmds/join_pool.py", line 53, in join_pool
    assert wallet_client is not None
AssertionError

Daemon stopped


Second time has run correctly:

radxa@rock-4c-plus:/chia/foxy-gh-farmer$ sudo foxy-gh-farmer join-pool
Daemon not started yet
Starting daemon
chia_wallet: started
✅ Wallet synced
✅ All PlotNFTs are already pooling with Foxy, nothing to do
Daemon stopped

third time:

has failed agian:

radxa@rock-4c-plus:/chia/foxy-gh-farmer$ sudo foxy-gh-farmer join-pool
[sudo] password for radxa:
Daemon not started yet
Starting daemon
chia_wallet: started
Connection error. Check if wallet rpc is running at 29256
This is normal if wallet is still starting up
Exception from 'wallet' :
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/chia/cmds/cmds_util.py", line 106, in get_any_service_client
    yield None, config
  File "/usr/local/lib/python3.9/dist-packages/foxy_gh_farmer/cmds/join_pool.py", line 53, in join_pool
    assert wallet_client is not None
AssertionError

Daemon stopped

**Comment by felixbrucker** [comment]
Can you try with the current `main`? i think the issue should be fixed for you now 👍

**Comment by liliput629** [comment]
Hi,

i recompiled , **run correctly** two times consecutivly:


radxa@rock-4c-plus:/chia/foxy-gh-farmer$ sudo foxy-gh-farmer  join-pool
Daemon not started yet
Starting daemon
chia_wallet: started
✅ Wallet synced
✅ All PlotNFTs are already pooling with Foxy, nothing to do
Daemon stopped
radxa@rock-4c-plus:/chia/foxy-gh-farmer$ sudo foxy-gh-farmer  join-pool
Daemon not started yet
Starting daemon
chia_wallet: started
✅ Wallet synced
✅ All PlotNFTs are already pooling with Foxy, nothing to do
Daemon stopped

thanks

**Comment by felixbrucker** [comment]
Great, thanks for confirming 👍 

Fixed by https://github.com/foxypool/foxy-gh-farmer/commit/13d9f86dbc2d131ec55737bcad96aa0ba4c00913
